const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE='resume-tailor:details:v4', OUTPUT='resume-tailor:output:v4';
const def={
 profile:{fullName:'',email:'',phone:'',location:'',linkedin:'',github:'',website:'',seniority:'',roleBased:false,webhookMode:'none',webhookUrl:'',work:[{enabled:true,company:'',period:'',location:'',role:'',bulletPoints:6}],education:[{institution:'',degree:'',period:''}],certifications:[{institution:'',certification:'',date:''}]},
 design:{fontFamily:'Helvetica Neue',fontSize:10,fontColor:'#333333',pageMargin:.75,lineSpacing:1.2,sectionGap:12,headerName:'',headerRole:'',showContact:true,nameFontSize:24,nameColor:'#003800',nameBold:true,roleFontSize:18,roleColor:'#000000',roleBold:true,contactColor:'#0f0f0f',headerAlign:'center',titlePosition:'below',sectionTitleSize:12,sectionTitleColor:'#3e702c',sectionTitleBold:true,sectionTitleCaps:true,sectionTitleBorder:true,sectionTitleAlign:'left',experienceLayout:'single',boostEducation:false,sections:{summary:true,skills:true,experience:true,education:true,certifications:true}},
 jobDescription:'', autoDownload:false
};
const clone=o=>JSON.parse(JSON.stringify(o));
function deepMerge(a,b){if(!b||typeof b!=='object')return a;for(const k of Object.keys(b)){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k]&&typeof a[k]==='object'&&!Array.isArray(a[k]))deepMerge(a[k],b[k]);else a[k]=b[k]}return a}
let state=deepMerge(clone(def),JSON.parse(localStorage.getItem(STORAGE)||'{}'));let output=JSON.parse(localStorage.getItem(OUTPUT)||'null');let zoom=.69;
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));buildPrompt();renderResume();}
function gotoPage(p){$$('.page').forEach(x=>x.classList.remove('active'));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#page-'+p).classList.add('active');if(p==='preview'){buildPrompt();renderResume();}}
$$('.nav-btn').forEach(b=>b.onclick=()=>gotoPage(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>gotoPage(b.dataset.go));
$('#themeBtn').onclick=()=>document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark';
function bind(id,obj,key,type='value'){const el=$('#'+id);el[type]=obj[key]??(type==='checked'?false:'');el.addEventListener(type==='checked'?'change':'input',()=>{obj[key]=type==='checked'?el.checked:el.value;save()})}
['fullName','email','phone','location','linkedin','github','website','seniority'].forEach(k=>bind(k,state.profile,k));bind('roleBased',state.profile,'roleBased','checked');bind('webhookMode',state.profile,'webhookMode');bind('webhookUrl',state.profile,'webhookUrl');
$('#webhookMode').onchange=()=>{state.profile.webhookMode=$('#webhookMode').value;$('#webhookUrl').classList.toggle('hidden',state.profile.webhookMode!=='metadata');save()};$('#webhookUrl').classList.toggle('hidden',state.profile.webhookMode!=='metadata');
function renderWork(){const r=$('#workList');r.innerHTML='';state.profile.work.forEach((w,i)=>{const d=document.createElement('div');d.className='repeat-item '+(state.profile.roleBased?'role-on':'');d.innerHTML=`<div class="repeat-grid"><label>Company Name<input data-k="company" value="${esc(w.company)}"></label><label>Period<input data-k="period" value="${esc(w.period)}"></label><label>Location<input data-k="location" value="${esc(w.location)}"></label><label>Bullet Points<input data-k="bulletPoints" type="number" min="1" max="20" value="${w.bulletPoints||6}"></label><button class="remove-btn">×</button></div><div class="repeat-grid" style="grid-template-columns:1.2fr 1fr"><label>Role / Job Title<input data-k="role" value="${esc(w.role)}"></label><label class="include-role">Include this role <input data-k="enabled" type="checkbox" ${w.enabled!==false?'checked':''}></label></div>`;d.querySelectorAll('input').forEach(el=>el.oninput=()=>{w[el.dataset.k]=el.type==='checkbox'?el.checked:el.dataset.k==='bulletPoints'?Math.max(1,Math.min(20,+el.value||1)):el.value;save()});d.querySelector('.remove-btn').onclick=()=>{state.profile.work.splice(i,1);renderWork();save()};r.appendChild(d)})}
function renderEducation(){const r=$('#educationList');r.innerHTML='';state.profile.education.forEach((e,i)=>{const d=document.createElement('div');d.className='repeat-item';d.innerHTML=`<div class="repeat-grid education"><label>Institution<input data-k="institution" value="${esc(e.institution)}"></label><label>Degree and Major<input data-k="degree" value="${esc(e.degree)}"></label><label>Period<input data-k="period" value="${esc(e.period)}"></label><button class="remove-btn">×</button></div>`;d.querySelectorAll('input').forEach(el=>el.oninput=()=>{e[el.dataset.k]=el.value;save()});d.querySelector('.remove-btn').onclick=()=>{state.profile.education.splice(i,1);renderEducation();save()};r.appendChild(d)})}
function renderCerts(){const r=$('#certificationList');r.innerHTML='';state.profile.certifications.forEach((e,i)=>{const d=document.createElement('div');d.className='repeat-item';d.innerHTML=`<div class="repeat-grid certification"><label>Institution<input data-k="institution" value="${esc(e.institution)}"></label><label>Certification<input data-k="certification" value="${esc(e.certification)}"></label><label>Date<input data-k="date" value="${esc(e.date)}"></label><button class="remove-btn">×</button></div>`;d.querySelectorAll('input').forEach(el=>el.oninput=()=>{e[el.dataset.k]=el.value;save()});d.querySelector('.remove-btn').onclick=()=>{state.profile.certifications.splice(i,1);renderCerts();save()};r.appendChild(d)})}
$('#addWork').onclick=()=>{state.profile.work.push({enabled:true,company:'',period:'',location:'',role:'',bulletPoints:6});renderWork();save()};$('#addEducation').onclick=()=>{state.profile.education.push({institution:'',degree:'',period:''});renderEducation();save()};$('#addCertification').onclick=()=>{state.profile.certifications.push({institution:'',certification:'',date:''});renderCerts();save()};$('#roleBased').onchange=()=>{state.profile.roleBased=$('#roleBased').checked;renderWork();save()};renderWork();renderEducation();renderCerts();
const d=state.design;
['fontFamily','fontSize','fontColorText','pageMargin','lineSpacing','sectionGap'].forEach(id=>{const key=id==='fontColorText'?'fontColor':id;const el=$('#'+id);el.value=d[key];el.oninput=()=>{d[key]=['fontSize','pageMargin','lineSpacing','sectionGap'].includes(id)?+el.value:el.value;if(id==='fontColorText')$('#fontColor').value=d.fontColor;save()}});
function bindNum(id,key){const el=$('#'+id);el.value=d[key];el.oninput=()=>{d[key]=+el.value;save()}}
function bindCheck(id,key){const el=$('#'+id);el.checked=!!d[key];el.onchange=()=>{d[key]=el.checked;save()}}
function bindColor(textId,colorId,key){$('#'+textId).value=d[key];$('#'+colorId).value=d[key];$('#'+textId).oninput=()=>{d[key]=$('#'+textId).value;try{$('#'+colorId).value=d[key]}catch{}save()};$('#'+colorId).oninput=()=>{d[key]=$('#'+colorId).value;$('#'+textId).value=d[key];save()}}
$('#fontColor').value=d.fontColor;$('#fontColor').oninput=()=>{d.fontColor=$('#fontColor').value;$('#fontColorText').value=d.fontColor;save()};
bindNum('nameFontSize','nameFontSize');bindColor('nameColorText','nameColor','nameColor');bindCheck('nameBold','nameBold');
bindNum('roleFontSize','roleFontSize');bindColor('roleColorText','roleColor','roleColor');bindCheck('roleBold','roleBold');
bindColor('contactColorText','contactColor','contactColor');bindCheck('showContact','showContact');
bindNum('sectionTitleSize','sectionTitleSize');bindColor('sectionTitleColorText','sectionTitleColor','sectionTitleColor');bindCheck('sectionTitleBold','sectionTitleBold');bindCheck('sectionTitleCaps','sectionTitleCaps');bindCheck('sectionTitleBorder','sectionTitleBorder');bindCheck('boostEducation','boostEducation');
function activeButtons(sel,key,valAttr){$$(sel).forEach(b=>{b.classList.toggle('active',b.dataset[valAttr]===d[key]);b.onclick=()=>{d[key]=b.dataset[valAttr];activeButtons(sel,key,valAttr);save()}})}
activeButtons('[data-header-align]','headerAlign','headerAlign');activeButtons('[data-title-position]','titlePosition','titlePosition');activeButtons('[data-section-align]','sectionTitleAlign','sectionAlign');activeButtons('[data-exp-layout]','experienceLayout','expLayout');
$$('[data-section-toggle]').forEach(el=>{el.checked=d.sections[el.dataset.sectionToggle]!==false;el.onchange=()=>{d.sections[el.dataset.sectionToggle]=el.checked;save()}});$('#customizeBtn').onclick=()=>$('#customizeDrawer').classList.toggle('hidden');$('#closeCustomize').onclick=()=>$('#customizeDrawer').classList.add('hidden');
$('#jobDescription').value=state.jobDescription;$('#jobDescription').oninput=()=>{state.jobDescription=$('#jobDescription').value;save()};$('#autoDownload').checked=state.autoDownload;$('#autoDownload').onchange=()=>{state.autoDownload=$('#autoDownload').checked;save()};
function workPrompt(){return state.profile.work.filter(w=>w.enabled!==false).map(w=>`- ${w.company||'Company'} | ${w.role||'Role not specified'} | ${w.period||'Period not specified'} | ${w.location||''} | ${w.bulletPoints||6} Bullet Points`).join('\n')}
function buildPrompt(){const p=state.profile;const certs=p.certifications.filter(x=>x.certification||x.institution).map(x=>`- ${x.certification||'Certification'} | ${x.institution||''} | ${x.date||''}`).join('\n');const edu=p.education.filter(x=>x.degree||x.institution).map(x=>`- ${x.degree||'Degree'} | ${x.institution||''} | ${x.period||''}`).join('\n');const prompt=`You are a resume generation engine.\nYour output MUST be exactly ONE valid JSON object inside a single code block.\nDo NOT include explanations, comments, markdown, headers, or text outside the JSON.\nDo NOT generate multiple code blocks.\nDo NOT ask questions.\nIf any rule fails, STOP and return a plain text error message instead of JSON.\n\n========================================\nCANDIDATE PROFILE\n========================================\nSeniority Level: ${p.seniority||'Not specified'}\nWork Experience:\n${workPrompt()||'- None'}\nEducation:\n${edu||'- None'}\nCertifications:\n${certs||'- None'}\n\n========================================\nOUTPUT FORMAT\n========================================\n{\n  "company": "",\n  "title": "",\n  "summary": "",\n  "skills": [{"Category": ["Skill"]}],\n  "experience": [{"company":"","title":"","location":"","period":"","sentences":["..."]}],\n  "education": [{"institution":"","degree":"","period":""}],\n  "certifications": [{"institution":"","certification":"","date":""}]\n}\n\n========================================\nRULES\n========================================\n- Tailor strongly to the job description while preserving the candidate's real companies, periods, education and certifications.\n- Use ATS keywords naturally.\n- Keep the configured bullet count for each enabled role exactly.\n- If role-based mode is enabled, omit any role marked disabled.\n- Do not invent certifications, degrees, security clearances, employers or dates.\n- Each experience sentence should be specific, achievement-oriented, and end with a period.\n\n========================================\nJOB DESCRIPTION\n========================================\n${state.jobDescription}`;$('#aiPrompt').value=prompt;return prompt}
$('#buildPrompt').onclick=buildPrompt;$('#copyPrompt').onclick=async()=>{await navigator.clipboard.writeText(buildPrompt()).catch(()=>{});};buildPrompt();
function normalize(txt){return txt.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'')}
function parseJson(){try{return {ok:true,obj:JSON.parse(normalize($('#jsonResponse').value))}}catch(e){return {ok:false,error:e.message}}}
function applyJson(){const p=parseJson();if(!p.ok){$('#jsonError').textContent=p.error;return}output=p.obj;localStorage.setItem(OUTPUT,JSON.stringify(output));$('#jsonError').textContent='';renderResume()}
$('#applyJson').onclick=applyJson;$('#jsonResponse').oninput=()=>{const p=parseJson();if(p.ok){output=p.obj;localStorage.setItem(OUTPUT,JSON.stringify(output));renderResume()}};$('#formatJson').onclick=()=>{const p=parseJson();if(p.ok){$('#jsonResponse').value=JSON.stringify(p.obj,null,2);applyJson()}};
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#downloadJson').onclick=()=>{if(output)download('tailored-resume.json',JSON.stringify(output,null,2))};
$('#saveDetailsBtn').onclick=()=>download('resume-tailor-details.json',JSON.stringify({version:4,...state,output},null,2));$('#loadDetailsBtn').onclick=()=>$('#loadDetailsInput').click();$('#loadDetailsInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const j=JSON.parse(await f.text());state=deepMerge(clone(def),j);output=j.output||null;localStorage.setItem(STORAGE,JSON.stringify(state));localStorage.setItem(OUTPUT,JSON.stringify(output));location.reload()}catch{alert('Invalid details JSON')}};
async function tailor(){if(state.jobDescription.trim().length<40){$('#runStatus').textContent='Paste a complete job description first.';return}$('#tailorBtn').disabled=true;$('#tailorBtn').textContent='Tailoring…';$('#runStatus').textContent='Generating tailored resume…';try{const r=await fetch('/api/tailor',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({profile:{...state.profile,workExperiences:state.profile.work.filter(w=>w.enabled!==false).map(w=>({company:w.company,dates:w.period,title:w.role,location:w.location,bulletPoints:w.bulletPoints})),educations:state.profile.education.map(e=>({degreeMajor:e.degree,school:e.institution,dates:e.period})),certifications:state.profile.certifications},jobDescription:state.jobDescription})});const data=await r.json();if(!r.ok)throw Error(data.error||'Tailoring failed');output=data.resume;$('#jsonResponse').value=JSON.stringify(output,null,2);localStorage.setItem(OUTPUT,JSON.stringify(output));renderResume();$('#runStatus').textContent='Tailored resume generated.';if(state.autoDownload)setTimeout(()=>window.print(),350)}catch(e){$('#runStatus').textContent=e.message}finally{$('#tailorBtn').disabled=false;$('#tailorBtn').textContent='Tailor Resume'}}
$('#tailorBtn').onclick=tailor;
function resumeModel(){const p=state.profile,o=output||{};return {name:d.headerName||p.fullName||'Your Name',role:d.headerRole||o.title||state.profile.work.find(w=>w.enabled!==false)?.role||'Professional',summary:o.summary||'Complete your profile and generate a tailored resume to populate this section.',skills:Array.isArray(o.skills)?o.skills:[],experience:Array.isArray(o.experience)&&o.experience.length?o.experience:state.profile.work.filter(w=>w.enabled!==false).map(w=>({company:w.company,title:w.role,period:w.period,location:w.location,sentences:[]})),education:Array.isArray(o.education)&&o.education.length?o.education:state.profile.education,certifications:Array.isArray(o.certifications)&&o.certifications.length?o.certifications:state.profile.certifications,contact:[p.email,p.phone,p.linkedin,p.location].filter(Boolean).join(' | ')}}
function section(title,body){return `<section class="resume-section"><h3>${title}</h3>${body}</section>`}
function renderResume(){
  const m=resumeModel(), root=$('#pagesWrap'); root.innerHTML='';
  const page=document.createElement('div'); page.className='resume-page';
  page.style.setProperty('--resume-font',`'${d.fontFamily}',Arial,sans-serif`); page.style.setProperty('--resume-size',`${d.fontSize}pt`); page.style.setProperty('--page-margin',`${d.pageMargin}in`); page.style.setProperty('--line-spacing',d.lineSpacing); page.style.setProperty('--section-gap',`${d.sectionGap}pt`); page.style.color=d.fontColor;
  const headerStyle=`--name-size:${d.nameFontSize}pt;--name-color:${d.nameColor};--name-weight:${d.nameBold?700:400};--role-size:${d.roleFontSize}pt;--role-color:${d.roleColor};--role-weight:${d.roleBold?700:400};--contact-color:${d.contactColor};--header-align:${d.headerAlign==='left'?'left':'center'};--section-title-size:${d.sectionTitleSize}pt;--section-title-color:${d.sectionTitleColor};--section-title-weight:${d.sectionTitleBold?700:400};--section-title-transform:${d.sectionTitleCaps?'uppercase':'none'};--section-title-border:${d.sectionTitleBorder?'1px solid '+d.sectionTitleColor:'none'};--section-title-align:${d.sectionTitleAlign};`;
  page.setAttribute('style',(page.getAttribute('style')||'')+headerStyle);
  let header='';
  if(d.titlePosition==='next') header=`<div class="header-next"><div class="resume-name">${esc(m.name)}</div><div class="resume-role">${esc(m.role)}</div></div>`;
  else header=`<div class="resume-name">${esc(m.name)}</div><div class="resume-role">${esc(m.role)}</div>`;
  let html=`<div class="resume-header ${d.headerAlign}">${header}${d.showContact?`<div class="contact-row">${esc(m.contact)}</div>`:''}</div>`;
  const blocks=[];
  if(d.sections.summary) blocks.push({k:'summary',html:section('Professional Summary',`<p>${esc(m.summary)}</p>`)});
  if(d.sections.skills&&m.skills.length){const sk=m.skills.map(g=>Object.entries(g).map(([k,v])=>`<div class="skill-row"><b>${esc(k)}:</b> ${esc(Array.isArray(v)?v.join(', '):v)}</div>`).join('')).join('');blocks.push({k:'skills',html:section('Technical Skills',sk)})}
  if(d.sections.experience){let ex='';m.experience.forEach((e,i)=>{const source=state.profile.work.find(w=>w.company===e.company)||state.profile.work[i]||{};const title=e.title||source.role||'',company=e.company||source.company||'',period=e.period||source.period||'',loc=e.location||source.location||'';let head='';if(d.experienceLayout==='company')head=`<div class="job-two"><span><b>${esc(company)}</b><small>${esc(title)}</small></span><span>${esc(loc)}<small>${esc(period)}</small></span></div>`;else if(d.experienceLayout==='role')head=`<div class="job-two"><span><b>${esc(title)}</b><small>${esc(company)}</small></span><span>${esc(period)}<small>${esc(loc)}</small></span></div>`;else head=`<div class="job-header"><span><b>${esc(company)}</b> – ${esc(title)}</span><span>${esc(period)}${loc?' | '+esc(loc):''}</span></div>`;ex+=`<div class="job-block">${head}${Array.isArray(e.sentences)&&e.sentences.length?`<ul>${e.sentences.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</div>`});blocks.push({k:'experience',html:section('Work Experience',ex)})}
  if(d.sections.education&&m.education.length){const ed=m.education.filter(e=>e.degree||e.institution).map(e=>`<div class="edu-line"><span><b>${esc(e.degree||e.degreeMajor||'')}</b>${(e.institution||e.school)?` — ${esc(e.institution||e.school)}`:''}</span><span>${esc(e.period||e.dates||'')}</span></div>`).join('');if(ed)blocks.push({k:'education',html:section('Education',ed)})}
  if(d.sections.certifications&&m.certifications.length){const ce=m.certifications.filter(c=>c.certification||c.institution).map(c=>`<div class="cert-line"><span><b>${esc(c.certification||'')}</b>${c.institution?` — ${esc(c.institution)}`:''}</span><span>${esc(c.date||'')}</span></div>`).join('');if(ce)blocks.push({k:'certifications',html:section('Certifications',ce)})}
  if(d.boostEducation){const ei=blocks.findIndex(x=>x.k==='education'),si=blocks.findIndex(x=>x.k==='skills');if(ei>-1&&si>-1){const [b]=blocks.splice(ei,1);const nsi=blocks.findIndex(x=>x.k==='skills');blocks.splice(nsi,0,b)}}
  html+=blocks.map(x=>x.html).join(''); page.innerHTML=html; page.style.transform=`scale(${zoom})`; root.appendChild(page); $('#pageTotal').textContent='1'; $('#docId').textContent=(output?.company||'resume').slice(0,18); const thumbs=$('#thumbs'); thumbs.innerHTML='<div class="thumb active" data-page="1"></div>'; $('#zoomLabel').textContent=Math.round(zoom*100)+'%';
}
$('#zoomIn').onclick=()=>{zoom=Math.min(1.2,zoom+.05);renderResume()};$('#zoomOut').onclick=()=>{zoom=Math.max(.4,zoom-.05);renderResume()};$('#downloadPdfBtn').onclick=()=>window.print();$('#viewerDownload').onclick=()=>window.print();
renderResume();if(output)$('#jsonResponse').value=JSON.stringify(output,null,2);
