import http from 'node:http';import {readFile,stat} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const PORT=Number(process.env.PORT||8080);const KEY=process.env.OPENAI_API_KEY||'';const MODEL=process.env.OPENAI_MODEL||'gpt-6-sol';
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};
const clean=(v,n=200000)=>String(v??'').trim().slice(0,n);function send(res,s,d){const b=JSON.stringify(d);res.writeHead(s,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(b)}
async function body(req){const a=[];let n=0;for await(const c of req){n+=c.length;if(n>2500000)throw Error('Request too large');a.push(c)}return JSON.parse(Buffer.concat(a).toString()||'{}')}
function prompt(p,jd){const work=(p.workExperiences||[]).map(e=>`- ${clean(e.company,200)} | ${clean(e.title,160)} | ${clean(e.dates,100)} | ${clean(e.location,120)} | ${Math.max(1,Math.min(20,+e.bulletPoints||6))} Bullet Points`).join('\n');const edu=(p.educations||[]).map(e=>`- ${clean(e.degreeMajor,240)} | ${clean(e.school,240)} | ${clean(e.dates,100)}`).join('\n');const cert=(p.certifications||[]).map(c=>`- ${clean(c.certification,240)} | ${clean(c.institution,240)} | ${clean(c.date,100)}`).join('\n');return `You are a resume generation engine.\nYour output MUST be exactly ONE valid JSON object and nothing else.\nDo NOT include markdown fences or commentary.\n\nCANDIDATE PROFILE\nSeniority Level: ${clean(p.seniority,120)||'Not specified'}\nWork Experience:\n${work||'- None'}\nEducation:\n${edu||'- None'}\nCertifications:\n${cert||'- None'}\n\nOUTPUT JSON SCHEMA\n{\n "company":"",\n "title":"",\n "summary":"",\n "skills":[{"Category":["Skill"]}],\n "experience":[{"company":"","title":"","location":"","period":"","sentences":["..."]}],\n "education":[{"institution":"","degree":"","period":""}],\n "certifications":[{"institution":"","certification":"","date":""}]\n}\n\nRULES\n- Strongly tailor to the job description and ATS keywords.\n- Preserve actual company names, periods, education and certifications.\n- Match the requested bullet count per work entry exactly.\n- Do not invent certifications, degrees, clearances, companies, or dates.\n- Each experience sentence should be concrete and achievement-oriented and end with a period.\n\nJOB DESCRIPTION\n${clean(jd,180000)}`}
function extract(x){if(typeof x?.output_text==='string')return x.output_text;let s='';for(const i of x?.output||[])for(const c of i?.content||[])if(c?.type==='output_text')s+=c.text||'';return s.trim()}
async function tailor(req,res){let x;try{x=await body(req)}catch(e){return send(res,400,{error:e.message})}if(!KEY)return send(res,503,{error:'OPENAI_API_KEY is not configured on the server.'});if(clean(x.jobDescription).length<40)return send(res,400,{error:'Paste a complete job description first.'});let r;try{r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${KEY}`,'content-type':'application/json'},body:JSON.stringify({model:MODEL,input:prompt(x.profile||{},x.jobDescription),max_output_tokens:14000})})}catch(e){return send(res,502,{error:e.message})}const raw=await r.json().catch(()=>({}));if(!r.ok)return send(res,400,{error:raw?.error?.message||'AI request failed'});try{const obj=JSON.parse(extract(raw).replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''));return send(res,200,{resume:obj,model:raw.model||MODEL})}catch(e){return send(res,502,{error:'The AI returned invalid JSON: '+e.message})}}
async function staticFile(req,res){let u=new URL(req.url,`http://${req.headers.host||'localhost'}`).pathname;if(u==='/')u='/index.html';const f=path.resolve(__dirname,'.'+decodeURIComponent(u));if(!f.startsWith(__dirname+path.sep)){res.writeHead(403);return res.end('Forbidden')}try{const st=await stat(f);const q=st.isDirectory()?path.join(f,'index.html'):f;const data=await readFile(q);res.writeHead(200,{'content-type':mime[path.extname(q)]||'application/octet-stream'});res.end(data)}catch{res.writeHead(404);res.end('Not found')}}
http.createServer((req,res)=>{if(req.method==='POST'&&req.url?.split('?')[0]==='/api/tailor')return tailor(req,res);if(req.method==='GET')return staticFile(req,res);res.writeHead(405);res.end('Method not allowed')}).listen(PORT,'0.0.0.0',()=>console.log(`Resume Tailor running on ${PORT}`));
